import valorant from "./../assets/valorant.webp";
import overwatch2 from "./../assets/overwatch2.webp";
import lol from "./../assets/lol.webp";
import gta5 from "./../assets/gta5.webp";
import er from "./../assets/er.webp";

export const gameOptions = [
  { value: "valorant", label: "Valorant", image: valorant },
  { value: "overwatch2", label: "Overwatch2", image: overwatch2 },
  { value: "lol", label: "LOL", image: lol },
  { value: "gta5", label: "GTA5", image: gta5 },
  { value: "er", label: "Eternal Return", image: er },
];

export const characterOptions = {
  valorant: [
    { value: "gekko", label: "게코" },
    { value: "neon", label: "네온" },
    { value: "deadlock", label: "데드록" },
    { value: "reyna", label: "레이나" },
    { value: "raze", label: "레이즈" },
    { value: "vyse", label: "바이스" },
    { value: "viper", label: "바이퍼" },
    { value: "breach", label: "브리치" },
    { value: "brimstone", label: "브림스톤" },
    { value: "cypher", label: "사이퍼" },
    { value: "sage", label: "세이지" },
    { value: "sova", label: "소바" },
    { value: "skye", label: "스카이" },
    { value: "astra", label: "아스트라" },
    { value: "iso", label: "아이소" },
    { value: "omen", label: "오멘" },
    { value: "yoru", label: "요루" },
    { value: "waylay", label: "웨이레이" },
    { value: "jett", label: "제트" },
    { value: "chamber", label: "체임버" },
    { value: "kayo", label: "케이/오" },
    { value: "clove", label: "클로브" },
    { value: "killjoy", label: "킬조이" },
    { value: "tejo", label: "테호" },
    { value: "fade", label: "페이드" },
    { value: "phoenix", label: "피닉스" },
    { value: "harbor", label: "하버" },
  ],
  overwatch2: [
    { value: "dva", label: "D.Va" },
    { value: "doomfist", label: "둠피스트" },
    { value: "ramattra", label: "라마트라" },
    { value: "reinhardt", label: "라인하르트" },
    { value: "wreckingball", label: "레킹볼" },
    { value: "roadhog", label: "로드호그" },
    { value: "mauga", label: "마우가" },
    { value: "sigma", label: "시그마" },
    { value: "orisa", label: "오리사" },
    { value: "winston", label: "원스턴" },
    { value: "zariya", label: "자리야" },
    { value: "junkerqueen", label: "정커퀸" },
    { value: "hazard", label: "해저드" },
    { value: "genji", label: "겐지" },
    { value: "reaper", label: "리퍼" },
    { value: "mei", label: "메이" },
    { value: "bastion", label: "바스티온" },
    { value: "venture", label: "벤처" },
    { value: "sojourn", label: "소전" },
    { value: "soldier", label: "솔저:76" },
    { value: "sombra", label: "솜브라" },
    { value: "symmetra", label: "시메트라" },
    { value: "ashe", label: "애쉬" },
    { value: "echo", label: "애코" },
    { value: "widowmaker", label: "위도우메이커" },
    { value: "junkrat", label: "정크랫" },
    { value: "cassidy", label: "캐서디" },
    { value: "torbjorn", label: "토르비욘" },
    { value: "tracer", label: "트레이서" },
    { value: "pharah", label: "파라" },
    { value: "freja", label: "프레야" },
    { value: "hanzo", label: "한조" },
    { value: "lifeweaver", label: "라이프위버" },
    { value: "lucio", label: "루시우" },
    { value: "mercy", label: "메르시" },
    { value: "moira", label: "모이라" },
    { value: "baptiste", label: "바티스트" },
    { value: "brigitte", label: "브리기테" },
    { value: "ana", label: "아나" },
    { value: "wuyang", label: "우양" },
    { value: "illari", label: "일리아리" },
    { value: "zenyatta", label: "젠야타" },
    { value: "juno", label: "주노" },
    { value: "kiriko", label: "키리코" },
  ],
  lol: [
    { value: "aatrox", label: "아트록스" },
    { value: "ahri", label: "아리" },
    { value: "akali", label: "아칼리" },
    { value: "akshan", label: "아크샨" },
    { value: "alistar", label: "알리스타" },
    { value: "ambessa", label: "암베사" },
    { value: "amumu", label: "아무무" },
    { value: "anivia", label: "애니비아" },
    { value: "annie", label: "애니" },
    { value: "aphelios", label: "아펠리오스" },
    { value: "ashe", label: "애쉬" },
    { value: "aurelionsol", label: "아우렐리온 솔" },
    { value: "aurora", label: "오로라" },
    { value: "azir", label: "아지르" },
    { value: "bard", label: "바드" },
    { value: "belveth", label: "벨베스" },
    { value: "blitzcrank", label: "블리츠크랭크" },
    { value: "brand", label: "브랜드" },
    { value: "braum", label: "브라움" },
    { value: "briar", label: "브라이어" },
    { value: "caitlyn", label: "케이틀린" },
    { value: "camille", label: "카밀" },
    { value: "cassiopeia", label: "카시오페아" },
    { value: "chogath", label: "초가스" },
    { value: "corki", label: "코르키" },
    { value: "darius", label: "다리우스" },
    { value: "diana", label: "다이애나" },
    { value: "drmundo", label: "문도 박사" },
    { value: "draven", label: "드레이븐" },
    { value: "ekko", label: "에코" },
    { value: "elise", label: "엘리스" },
    { value: "evelynn", label: "이블린" },
    { value: "ezreal", label: "이즈리얼" },
    { value: "fiddlesticks", label: "피들스틱" },
    { value: "lolfiora", label: "피오라" },
    { value: "fizz", label: "피즈" },
    { value: "galio", label: "갈리오" },
    { value: "gangplank", label: "갱플랭크" },
    { value: "garen", label: "가렌" },
    { value: "gnar", label: "나르" },
    { value: "gragas", label: "그라가스" },
    { value: "graves", label: "그레이브즈" },
    { value: "gwen", label: "그웬" },
    { value: "hecarim", label: "헤카림" },
    { value: "heimerdinger", label: "하이머딩거" },
    { value: "hwei", label: "흐웨이" },
    { value: "illaoi", label: "일라오이" },
    { value: "irelia", label: "이렐리아" },
    { value: "ivern", label: "아이번" },
    { value: "janna", label: "잔나" },
    { value: "jarvaniv", label: "자르반 4세" },
    { value: "jax", label: "잭스" },
    { value: "jayce", label: "제이스" },
    { value: "jhin", label: "진" },
    { value: "jinx", label: "징크스" },
    { value: "kaisa", label: "카이사" },
    { value: "kalista", label: "칼리스타" },
    { value: "karma", label: "카르마" },
    { value: "karthus", label: "카서스" },
    { value: "kassadin", label: "카사딘" },
    { value: "katarina", label: "카타리나" },
    { value: "kayle", label: "케일" },
    { value: "kayn", label: "케인" },
    { value: "kennen", label: "케넨" },
    { value: "khazix", label: "카직스" },
    { value: "kindred", label: "킨드레드" },
    { value: "kled", label: "클레드" },
    { value: "kogmaw", label: "코그모" },
    { value: "ksante", label: "크산테" },
    { value: "leblanc", label: "르블랑" },
    { value: "leesin", label: "리신" },
    { value: "leona", label: "레오나" },
    { value: "lillia", label: "릴리아" },
    { value: "lissandra", label: "리산드라" },
    { value: "lucian", label: "루시안" },
    { value: "lulu", label: "룰루" },
    { value: "lux", label: "럭스" },
    { value: "malphite", label: "말파이트" },
    { value: "malzahar", label: "말자하" },
    { value: "maokai", label: "마오카이" },
    { value: "masteryi", label: "마스터 이" },
    { value: "mel", label: "멜" },
    { value: "milio", label: "밀리오" },
    { value: "missfortune", label: "미스 포춘" },
    { value: "mordekaiser", label: "모데카이저" },
    { value: "morgana", label: "모르가나" },
    { value: "naafiri", label: "나피리" },
    { value: "nami", label: "나미" },
    { value: "nasus", label: "나서스" },
    { value: "nautilus", label: "노틸러스" },
    { value: "neeko", label: "니코" },
    { value: "nidalee", label: "니달리" },
    { value: "nilah", label: "닐라" },
    { value: "nocturne", label: "녹턴" },
    { value: "nunu", label: "누누와 윌럼프" },
    { value: "olaf", label: "올라프" },
    { value: "orianna", label: "오리아나" },
    { value: "ornn", label: "오른" },
    { value: "pantheon", label: "판테온" },
    { value: "poppy", label: "뽀삐" },
    { value: "pyke", label: "파이크" },
    { value: "qiyana", label: "키아나" },
    { value: "quinn", label: "퀸" },
    { value: "rakan", label: "라칸" },
    { value: "rammus", label: "람머스" },
    { value: "reksai", label: "렉사이" },
    { value: "rell", label: "렐" },
    { value: "renata", label: "레나타 글라스크" },
    { value: "renekton", label: "레넥톤" },
    { value: "rengar", label: "렝가" },
    { value: "riven", label: "리븐" },
    { value: "rumble", label: "럼블" },
    { value: "ryze", label: "라이즈" },
    { value: "samira", label: "사미라" },
    { value: "sejuani", label: "세주아니" },
    { value: "senna", label: "세나" },
    { value: "seraphine", label: "세라핀" },
    { value: "sett", label: "세트" },
    { value: "shaco", label: "샤코" },
    { value: "shen", label: "쉔" },
    { value: "shyvana", label: "쉬바나" },
    { value: "singed", label: "신지드" },
    { value: "sion", label: "사이온" },
    { value: "sivir", label: "시비르" },
    { value: "skarner", label: "스카너" },
    { value: "smolder", label: "스몰더" },
    { value: "sona", label: "소나" },
    { value: "soraka", label: "소라카" },
    { value: "swain", label: "스웨인" },
    { value: "sylas", label: "사일러스" },
    { value: "syndra", label: "신드라" },
    { value: "tahmkench", label: "탐 켄치" },
    { value: "taliyah", label: "탈리야" },
    { value: "talon", label: "탈론" },
    { value: "taric", label: "타릭" },
    { value: "teemo", label: "티모" },
    { value: "thresh", label: "쓰레쉬" },
    { value: "tristana", label: "트리스타나" },
    { value: "trundle", label: "트런들" },
    { value: "tryndamere", label: "트린다미어" },
    { value: "twistedfate", label: "트위스티드 페이트" },
    { value: "twitch", label: "트위치" },
    { value: "udyr", label: "우디르" },
    { value: "urgot", label: "우르곳" },
    { value: "varus", label: "바루스" },
    { value: "vayne", label: "베인" },
    { value: "veigar", label: "베이가" },
    { value: "velkoz", label: "벨코즈" },
    { value: "vex", label: "벡스" },
    { value: "vi", label: "바이" },
    { value: "viego", label: "비에고" },
    { value: "viktor", label: "빅토르" },
    { value: "vladimir", label: "블라디미르" },
    { value: "volibear", label: "볼리베어" },
    { value: "warwick", label: "워윅" },
    { value: "wukong", label: "오공" },
    { value: "xayah", label: "자야" },
    { value: "xerath", label: "제라스" },
    { value: "xinzhao", label: "신 짜오" },
    { value: "yasuo", label: "야스오" },
    { value: "yone", label: "요네" },
    { value: "yorick", label: "요릭" },
    { value: "yuumi", label: "유미" },
    { value: "yunara", label: "유나라" },
    { value: "zac", label: "자크" },
    { value: "zed", label: "제드" },
    { value: "zeri", label: "제리" },
    { value: "ziggs", label: "직스" },
    { value: "zilean", label: "질리언" },
    { value: "zoe", label: "조이" },
    { value: "zyra", label: "자이라" },
  ],
  gta5: [
    { value: "doctor", label: "의사" },
    { value: "gang", label: "갱" },
    { value: "police", label: "경찰" },
    { value: "mechanic", label: "정비공" },
    { value: "businessman", label: "사업가" },
    { value: "etc", label: "기타" },
  ],

  er: [
    { value: "abigail", label: "아비게일" },
    { value: "adela", label: "아델라" },
    { value: "adina", label: "아디나" },
    { value: "adriana", label: "아드리아나" },
    { value: "aiden", label: "에이든" },
    { value: "alex", label: "알렉스" },
    { value: "alonso", label: "알론소" },
    { value: "arda", label: "아르다" },
    { value: "aya", label: "아야" },
    { value: "barbara", label: "바바라" },
    { value: "bernice", label: "버니스" },
    { value: "bianca", label: "비앙카" },
    { value: "blair", label: "블레어" },
    { value: "camilo", label: "카밀로" },
    { value: "cathy", label: "캐시" },
    { value: "celine", label: "셀린" },
    { value: "charlotte", label: "샬럿" },
    { value: "chiara", label: "키아라" },
    { value: "chloe", label: "클로에" },
    { value: "daniel", label: "다니엘" },
    { value: "darko", label: "다르코" },
    { value: "debimar", label: "데비&마를렌" },
    { value: "echion", label: "에키온" },
    { value: "elena", label: "엘레나" },
    { value: "eleven", label: "일레븐" },
    { value: "emma", label: "엠마" },
    { value: "estelle", label: "에스텔" },
    { value: "eva", label: "이바" },
    { value: "felix", label: "펠릭스" },
    { value: "erfiora", label: "피오라" },
    { value: "garnet", label: "가넷" },
    { value: "hart", label: "하트" },
    { value: "haze", label: "헤이즈" },
    { value: "henry", label: "헨리" },
    { value: "hisui", label: "히스이" },
    { value: "hyejin", label: "혜진" },
    { value: "hyunwoo", label: "현우" },
    { value: "irem", label: "이렘" },
    { value: "isaac", label: "아이작" },
    { value: "isol", label: "아이솔" },
    { value: "istvan", label: "이슈트반" },
    { value: "jackie", label: "재키" },
    { value: "jan", label: "얀" },
    { value: "jenny", label: "제니" },
    { value: "johann", label: "요한" },
    { value: "justyna", label: "유스티나" },
    { value: "karla", label: "칼라" },
    { value: "katja", label: "카티야" },
    { value: "kenneth", label: "케네스" },
    { value: "laura", label: "라우라" },
    { value: "leni", label: "레니" },
    { value: "lenore", label: "르노어" },
    { value: "lenox", label: "레녹스" },
    { value: "leon", label: "레온" },
    { value: "lidailin", label: "리 다이린" },
    { value: "luke", label: "루크" },
    { value: "lyanh", label: "이안" },
    { value: "magnus", label: "매그너스" },
    { value: "mai", label: "마이" },
    { value: "markus", label: "마커스" },
    { value: "martina", label: "마르티나" },
    { value: "mirka", label: "미르카" },
    { value: "nadine", label: "나딘" },
    { value: "nathapon", label: "나타폰" },
    { value: "niah", label: "니아" },
    { value: "nicky", label: "니키" },
    { value: "piolo", label: "피올로" },
    { value: "priya", label: "프리야" },
    { value: "rio", label: "리오" },
    { value: "rozzi", label: "로지" },
    { value: "shoichi", label: "쇼이치" },
    { value: "silvia", label: "실비아" },
    { value: "sissela", label: "시셀라" },
    { value: "sua", label: "수아" },
    { value: "tazia", label: "타지아" },
    { value: "theodore", label: "테오도르" },
    { value: "tia", label: "띠아" },
    { value: "tsubame", label: "츠바메" },
    { value: "vanya", label: "바냐" },
    { value: "william", label: "윌리엄" },
    { value: "xiukai", label: "쇼우" },
    { value: "xuelin", label: "슈린" },
    { value: "yuki", label: "유키" },
    { value: "yumin", label: "유민" },
    { value: "zahir", label: "자히르" },
  ],
};

export const positionOptions = {
  valorant: [
    { value: "duelist", label: "타격대" },
    { value: "initiator", label: "척후대" },
    { value: "sentinel", label: "감시자" },
    { value: "controller", label: "전략가" },
  ],
  overwatch2: [
    { value: "tanker", label: "탱커" },
    { value: "damage", label: "딜러" },
    { value: "healer", label: "힐러" },
  ],
  lol: [
    { value: "top", label: "탑" },
    { value: "mid", label: "미드" },
    { value: "jungle", label: "정글" },
    { value: "deal", label: "원딜" },
    { value: "support", label: "서포터" },
  ],
  er: [
    { value: "tanker", label: "탱커" },
    { value: "bruiser", label: "브루저" },
    { value: "assassin", label: "암살자" },
    { value: "melledps", label: "근딜" },
    { value: "rangeddps", label: "원딜" },
    { value: "support", label: "서포터" },
  ],
};
